project:
  type: website

website:
  title: "Katherine Mead"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    toc: true
    toc-location: left
    theme: cyborg
    css: styles.css
    fontsize: 1em
    page-layout: full
    navbar: false
    backgroundcolor: $gray-300
    fontcolor: black

    




